module.exports = {
  content: ["./**/*.liquid", "./**/*.js"], // all files Tailwind should scan
  safelist: [
    "bg-black",
    "bg-gray-700/40",
    "bg-gray-900/50",
    "text-white",
    "text-red-600",
    "text-red-900",
    "blur-sm",
    "bg-opacity-90",
    "hover:bg-gray-800",
    "rounded-2xl",
    "transition-colors",
    "font-semibold",
    "text-xl",
    "text-2xl",
    "md:text-2xl",
    "md:text-5xl",
    "text-4xl",
    "mb-4",
    "mb-6",
    "blur-xl",
    "blur-xs",
    "grid",
    "grid-cols-1",
    "grid-cols-2",
    "grid-cols-3",
    "grid-cols-4",
    "sm:grid-cols-2",
    "md:flex",
    "md:h-18",
    "md:hidden",
    "lg:grid-cols-3",
    "xl:grid-cols-4",
    "gap-6",
    "px-8",
    "py-3",
    "border",
    "border-gray-600",
    "border-3",
    "border-4",
    "border-amber-600",
    "border-yellow-600",
    "w-32",
    "w-72",
    "shrink-0",
    "scroll-smooth",
    "snap-x",
    "snap-mandatory",
    "h-32",
    "rounded",
    "rounded-md",
    "rounded-lg",
    "rounded-xl",
    "rounded-2xl",
    "rounded-full",
    "object-cover",
    "inline-block",
    "my-4",
    "mt-4",
    "py-10",
    "py-8",
    "py-6",
    "py-4",
    "py-2",
    "pl-2",
    "px-4",
    "px-6",
    "px-8",
    "px-10",
    "px-12",
    
  ],
  theme: {
    extend: {
      colors: {
        primary: '#1a202c', // example custom color
        secondary: '#2d3748'
      },
      spacing: {
        18: '4.5rem', // example custom spacing
      }
    },
  },
  plugins: [
    // e.g., require('@tailwindcss/forms'), // optional plugin
  ],
};
